// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_rank_item.proto

#ifndef PROTOBUF_msg_5frank_5fitem_2eproto__INCLUDED
#define PROTOBUF_msg_5frank_5fitem_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rank {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_5frank_5fitem_2eproto();
void protobuf_AssignDesc_msg_5frank_5fitem_2eproto();
void protobuf_ShutdownFile_msg_5frank_5fitem_2eproto();

class RankItemPacket;

// ===================================================================

class RankItemPacket : public ::google::protobuf::Message {
 public:
  RankItemPacket();
  virtual ~RankItemPacket();

  RankItemPacket(const RankItemPacket& from);

  inline RankItemPacket& operator=(const RankItemPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RankItemPacket& default_instance();

  void Swap(RankItemPacket* other);

  // implements Message ----------------------------------------------

  RankItemPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RankItemPacket& from);
  void MergeFrom(const RankItemPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint64 user_id() const;
  inline void set_user_id(::google::protobuf::uint64 value);

  // required int32 score = 2;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 2;
  inline ::google::protobuf::int32 score() const;
  inline void set_score(::google::protobuf::int32 value);

  // required uint32 rank = 3;
  inline bool has_rank() const;
  inline void clear_rank();
  static const int kRankFieldNumber = 3;
  inline ::google::protobuf::uint32 rank() const;
  inline void set_rank(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:rank.RankItemPacket)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_score();
  inline void clear_has_score();
  inline void set_has_rank();
  inline void clear_has_rank();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 user_id_;
  ::google::protobuf::int32 score_;
  ::google::protobuf::uint32 rank_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_msg_5frank_5fitem_2eproto();
  friend void protobuf_AssignDesc_msg_5frank_5fitem_2eproto();
  friend void protobuf_ShutdownFile_msg_5frank_5fitem_2eproto();

  void InitAsDefaultInstance();
  static RankItemPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// RankItemPacket

// required uint64 user_id = 1;
inline bool RankItemPacket::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RankItemPacket::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RankItemPacket::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RankItemPacket::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
  clear_has_user_id();
}
inline ::google::protobuf::uint64 RankItemPacket::user_id() const {
  return user_id_;
}
inline void RankItemPacket::set_user_id(::google::protobuf::uint64 value) {
  set_has_user_id();
  user_id_ = value;
}

// required int32 score = 2;
inline bool RankItemPacket::has_score() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RankItemPacket::set_has_score() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RankItemPacket::clear_has_score() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RankItemPacket::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline ::google::protobuf::int32 RankItemPacket::score() const {
  return score_;
}
inline void RankItemPacket::set_score(::google::protobuf::int32 value) {
  set_has_score();
  score_ = value;
}

// required uint32 rank = 3;
inline bool RankItemPacket::has_rank() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RankItemPacket::set_has_rank() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RankItemPacket::clear_has_rank() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RankItemPacket::clear_rank() {
  rank_ = 0u;
  clear_has_rank();
}
inline ::google::protobuf::uint32 RankItemPacket::rank() const {
  return rank_;
}
inline void RankItemPacket::set_rank(::google::protobuf::uint32 value) {
  set_has_rank();
  rank_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rank

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5frank_5fitem_2eproto__INCLUDED
