/* 
 * File:   CacheDBType.h
 * Author: Jehu Shaw
 * 
 * Created on 2014_8_4, 16:00
 */

#ifndef CACHEDBTYPE_H
#define	CACHEDBTYPE_H

enum eDBType {
	DB_TYPE_TINYINT,
	DB_TYPE_SMALLINT,
	DB_TYPE_MEDIUMINT,
	DB_TYPE_INTEGER,
	DB_TYPE_BIGINT,
	DB_TYPE_INT,
	DB_TYPE_BIT,
	DB_TYPE_REAL,
	DB_TYPE_DOUBLE,
	DB_TYPE_FLOAT,
	DB_TYPE_DECIMAL,
	DB_TYPE_NUMERIC,
	DB_TYPE_VARCHAR,
	DB_TYPE_CHAR,
	DB_TYPE_TIMESTAMP,
	DB_TYPE_DATETIME,
	DB_TYPE_DATE,
	DB_TYPE_TIME,
	DB_TYPE_YEAR,
	DB_TYPE_TINYBLOB,
	DB_TYPE_MEDIUMBLOB,
	DB_TYPE_LONGBLOB,
	DB_TYPE_BLOB,
	DB_TYPE_TINYTEXT,
	DB_TYPE_MEDIUMTEXT,
	DB_TYPE_LONGTEXT,
	DB_TYPE_TEXT,
	DB_TYPE_ENUM,
	DB_TYPE_SET,
	DB_TYPE_VARBINARY,
	DB_TYPE_BINARY,
	DB_TYPE_SIZE,
};


#endif /* CACHEDBTYPE_H */



