CREATE DATABASE IF NOT EXISTS node_control_centre DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS node_memcache DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS xyproject DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS xyproject_memcache DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci;
