// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_master_login.proto

#ifndef PROTOBUF_msg_5fmaster_5flogin_2eproto__INCLUDED
#define PROTOBUF_msg_5fmaster_5flogin_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace master {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_5fmaster_5flogin_2eproto();
void protobuf_AssignDesc_msg_5fmaster_5flogin_2eproto();
void protobuf_ShutdownFile_msg_5fmaster_5flogin_2eproto();

class LoginRequest;

// ===================================================================

class LoginRequest : public ::google::protobuf::Message {
 public:
  LoginRequest();
  virtual ~LoginRequest();

  LoginRequest(const LoginRequest& from);

  inline LoginRequest& operator=(const LoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRequest& default_instance();

  void Swap(LoginRequest* other);

  // implements Message ----------------------------------------------

  LoginRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRequest& from);
  void MergeFrom(const LoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 account = 1;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 1;
  inline ::google::protobuf::uint32 account() const;
  inline void set_account(::google::protobuf::uint32 value);

  // required string sessionkey = 2;
  inline bool has_sessionkey() const;
  inline void clear_sessionkey();
  static const int kSessionkeyFieldNumber = 2;
  inline const ::std::string& sessionkey() const;
  inline void set_sessionkey(const ::std::string& value);
  inline void set_sessionkey(const char* value);
  inline void set_sessionkey(const char* value, size_t size);
  inline ::std::string* mutable_sessionkey();
  inline ::std::string* release_sessionkey();
  inline void set_allocated_sessionkey(::std::string* sessionkey);

  // @@protoc_insertion_point(class_scope:master.LoginRequest)
 private:
  inline void set_has_account();
  inline void clear_has_account();
  inline void set_has_sessionkey();
  inline void clear_has_sessionkey();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* sessionkey_;
  ::google::protobuf::uint32 account_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_msg_5fmaster_5flogin_2eproto();
  friend void protobuf_AssignDesc_msg_5fmaster_5flogin_2eproto();
  friend void protobuf_ShutdownFile_msg_5fmaster_5flogin_2eproto();

  void InitAsDefaultInstance();
  static LoginRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// LoginRequest

// required uint32 account = 1;
inline bool LoginRequest::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRequest::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRequest::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRequest::clear_account() {
  account_ = 0u;
  clear_has_account();
}
inline ::google::protobuf::uint32 LoginRequest::account() const {
  return account_;
}
inline void LoginRequest::set_account(::google::protobuf::uint32 value) {
  set_has_account();
  account_ = value;
}

// required string sessionkey = 2;
inline bool LoginRequest::has_sessionkey() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginRequest::set_has_sessionkey() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginRequest::clear_has_sessionkey() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginRequest::clear_sessionkey() {
  if (sessionkey_ != &::google::protobuf::internal::kEmptyString) {
    sessionkey_->clear();
  }
  clear_has_sessionkey();
}
inline const ::std::string& LoginRequest::sessionkey() const {
  return *sessionkey_;
}
inline void LoginRequest::set_sessionkey(const ::std::string& value) {
  set_has_sessionkey();
  if (sessionkey_ == &::google::protobuf::internal::kEmptyString) {
    sessionkey_ = new ::std::string;
  }
  sessionkey_->assign(value);
}
inline void LoginRequest::set_sessionkey(const char* value) {
  set_has_sessionkey();
  if (sessionkey_ == &::google::protobuf::internal::kEmptyString) {
    sessionkey_ = new ::std::string;
  }
  sessionkey_->assign(value);
}
inline void LoginRequest::set_sessionkey(const char* value, size_t size) {
  set_has_sessionkey();
  if (sessionkey_ == &::google::protobuf::internal::kEmptyString) {
    sessionkey_ = new ::std::string;
  }
  sessionkey_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LoginRequest::mutable_sessionkey() {
  set_has_sessionkey();
  if (sessionkey_ == &::google::protobuf::internal::kEmptyString) {
    sessionkey_ = new ::std::string;
  }
  return sessionkey_;
}
inline ::std::string* LoginRequest::release_sessionkey() {
  clear_has_sessionkey();
  if (sessionkey_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sessionkey_;
    sessionkey_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LoginRequest::set_allocated_sessionkey(::std::string* sessionkey) {
  if (sessionkey_ != &::google::protobuf::internal::kEmptyString) {
    delete sessionkey_;
  }
  if (sessionkey) {
    set_has_sessionkey();
    sessionkey_ = sessionkey;
  } else {
    clear_has_sessionkey();
    sessionkey_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace master

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5fmaster_5flogin_2eproto__INCLUDED
