CREATE DATABASE IF NOT EXISTS node_control_centre DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS node_memcache DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE IF NOT EXISTS wonderful DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci;
