<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_master_data.proto

namespace GPBMetadata;

class MsgMasterData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aac010a156d73675f6d61737465725f646174612e70726f746f12046e6f64652284010a104d6173746572446174615061636b6574120b0a03636d6418012001280512100a087365727665726964180220012805120e0a06757365726964180320012804120c0a046461746118042001280c120e0a06726573756c7418052001281112110a0961646d696e6e616d6518062001280c12100a0861757468636f646518072001280c620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

