<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_master_data.proto

namespace Node;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>node.MasterDataPacket</code>
 */
class MasterDataPacket extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 cmd = 1;</code>
     */
    protected $cmd = 0;
    /**
     * Generated from protobuf field <code>int32 serverid = 2;</code>
     */
    protected $serverid = 0;
    /**
     * Generated from protobuf field <code>uint64 userid = 3;</code>
     */
    protected $userid = 0;
    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>sint32 result = 5;</code>
     */
    protected $result = 0;
    /**
     * Generated from protobuf field <code>bytes adminname = 6;</code>
     */
    protected $adminname = '';
    /**
     * Generated from protobuf field <code>bytes authcode = 7;</code>
     */
    protected $authcode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $cmd
     *     @type int $serverid
     *     @type int|string $userid
     *     @type string $data
     *     @type int $result
     *     @type string $adminname
     *     @type string $authcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MsgMasterData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 cmd = 1;</code>
     * @return int
     */
    public function getCmd()
    {
        return $this->cmd;
    }

    /**
     * Generated from protobuf field <code>int32 cmd = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCmd($var)
    {
        GPBUtil::checkInt32($var);
        $this->cmd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 serverid = 2;</code>
     * @return int
     */
    public function getServerid()
    {
        return $this->serverid;
    }

    /**
     * Generated from protobuf field <code>int32 serverid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setServerid($var)
    {
        GPBUtil::checkInt32($var);
        $this->serverid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 userid = 3;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>uint64 userid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 result = 5;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>sint32 result = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkInt32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes adminname = 6;</code>
     * @return string
     */
    public function getAdminname()
    {
        return $this->adminname;
    }

    /**
     * Generated from protobuf field <code>bytes adminname = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAdminname($var)
    {
        GPBUtil::checkString($var, False);
        $this->adminname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes authcode = 7;</code>
     * @return string
     */
    public function getAuthcode()
    {
        return $this->authcode;
    }

    /**
     * Generated from protobuf field <code>bytes authcode = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthcode($var)
    {
        GPBUtil::checkString($var, False);
        $this->authcode = $var;

        return $this;
    }

}

