#!/bin/bash

\cp -vf './Shared/bin/Debug/libShared.so' './Shared/bin/Debug/libShared.so.1.0.0'
\cp -vf './Shared/bin/Release/libShared.so' './Shared/bin/Release/libShared.so.1.0.0'

\cp -vf './Shared/bin/Debug/libShared.so.1.0.0' '../libs/linux32/shared/debug'
\cp -vf './Shared/bin/Release/libShared.so.1.0.0' '../libs/linux32/shared/release'


\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1.0.0' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../cache_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../cache_server/bin/linux32/Debug'


\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1.0.0' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../cache_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../cache_server/bin/linux32/Release'




\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1' '../../game_client/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1.0.0' '../../game_client/bin/linux32/Debug'

\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1' '../../game_client/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1.0.0' '../../game_client/bin/linux32/Release'



\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1.0.0' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../game_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../game_server/bin/linux32/Debug'

\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1.0.0' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../game_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../game_server/bin/linux32/Release'



\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1.0.0' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../login_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../login_server/bin/linux32/Debug'

\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1.0.0' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../login_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../login_server/bin/linux32/Release'


\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1.0.0' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../master_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../master_server/bin/linux32/Debug'

\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1.0.0' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../master_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../master_server/bin/linux32/Release'


\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1.0.0' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../agent_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../agent_server/bin/linux32/Debug'

\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1.0.0' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../agent_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../agent_server/bin/linux32/Release'


\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1.0.0' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../rank_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../rank_server/bin/linux32/Debug'

\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1.0.0' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../rank_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../rank_server/bin/linux32/Release'


\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/shared/debug/libShared.so.1.0.0' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../servant_server/bin/linux32/Debug'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../servant_server/bin/linux32/Debug'

\cp -vf '../libs/linux32/libcurl/libcurl.so' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/libcurl/libcurl.so.4.3.0' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient.so.20.3.0' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/mysql/libmysqlclient20' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/shared/release/libShared.so.1.0.0' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb-6.2.so' '../../servant_server/bin/linux32/Release'
\cp -vf '../libs/linux32/berkeleydb/libdb_stl-6.2.so' '../../servant_server/bin/linux32/Release'


