// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_packet.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_map_5fpacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_map_5fpacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common_packet.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_map_5fpacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_map_5fpacket_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_map_5fpacket_2eproto;
namespace game {
class MapCharacterPacket;
class MapCharacterPacketDefaultTypeInternal;
extern MapCharacterPacketDefaultTypeInternal _MapCharacterPacket_default_instance_;
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> ::game::MapCharacterPacket* Arena::CreateMaybeMessage<::game::MapCharacterPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace game {

// ===================================================================

class MapCharacterPacket :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.MapCharacterPacket) */ {
 public:
  MapCharacterPacket();
  virtual ~MapCharacterPacket();

  MapCharacterPacket(const MapCharacterPacket& from);
  MapCharacterPacket(MapCharacterPacket&& from) noexcept
    : MapCharacterPacket() {
    *this = ::std::move(from);
  }

  inline MapCharacterPacket& operator=(const MapCharacterPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapCharacterPacket& operator=(MapCharacterPacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MapCharacterPacket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MapCharacterPacket* internal_default_instance() {
    return reinterpret_cast<const MapCharacterPacket*>(
               &_MapCharacterPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MapCharacterPacket& a, MapCharacterPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(MapCharacterPacket* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MapCharacterPacket* New() const final {
    return CreateMaybeMessage<MapCharacterPacket>(nullptr);
  }

  MapCharacterPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MapCharacterPacket>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MapCharacterPacket& from);
  void MergeFrom(const MapCharacterPacket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapCharacterPacket* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.MapCharacterPacket";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_map_5fpacket_2eproto);
    return ::descriptor_table_map_5fpacket_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 3,
    kPosFieldNumber = 4,
    kFaceFieldNumber = 5,
    kUseridFieldNumber = 1,
    kCfgidFieldNumber = 2,
  };
  // string name = 3;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .game.VectorPacket pos = 4;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::game::VectorPacket& pos() const;
  ::game::VectorPacket* release_pos();
  ::game::VectorPacket* mutable_pos();
  void set_allocated_pos(::game::VectorPacket* pos);
  private:
  const ::game::VectorPacket& _internal_pos() const;
  ::game::VectorPacket* _internal_mutable_pos();
  public:

  // .game.VectorPacket face = 5;
  bool has_face() const;
  private:
  bool _internal_has_face() const;
  public:
  void clear_face();
  const ::game::VectorPacket& face() const;
  ::game::VectorPacket* release_face();
  ::game::VectorPacket* mutable_face();
  void set_allocated_face(::game::VectorPacket* face);
  private:
  const ::game::VectorPacket& _internal_face() const;
  ::game::VectorPacket* _internal_mutable_face();
  public:

  // uint64 userid = 1;
  void clear_userid();
  ::PROTOBUF_NAMESPACE_ID::uint64 userid() const;
  void set_userid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_userid() const;
  void _internal_set_userid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 cfgid = 2;
  void clear_cfgid();
  ::PROTOBUF_NAMESPACE_ID::uint32 cfgid() const;
  void set_cfgid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cfgid() const;
  void _internal_set_cfgid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:game.MapCharacterPacket)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::game::VectorPacket* pos_;
  ::game::VectorPacket* face_;
  ::PROTOBUF_NAMESPACE_ID::uint64 userid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cfgid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_map_5fpacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MapCharacterPacket

// uint64 userid = 1;
inline void MapCharacterPacket::clear_userid() {
  userid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MapCharacterPacket::_internal_userid() const {
  return userid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MapCharacterPacket::userid() const {
  // @@protoc_insertion_point(field_get:game.MapCharacterPacket.userid)
  return _internal_userid();
}
inline void MapCharacterPacket::_internal_set_userid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  userid_ = value;
}
inline void MapCharacterPacket::set_userid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:game.MapCharacterPacket.userid)
}

// uint32 cfgid = 2;
inline void MapCharacterPacket::clear_cfgid() {
  cfgid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapCharacterPacket::_internal_cfgid() const {
  return cfgid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapCharacterPacket::cfgid() const {
  // @@protoc_insertion_point(field_get:game.MapCharacterPacket.cfgid)
  return _internal_cfgid();
}
inline void MapCharacterPacket::_internal_set_cfgid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  cfgid_ = value;
}
inline void MapCharacterPacket::set_cfgid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cfgid(value);
  // @@protoc_insertion_point(field_set:game.MapCharacterPacket.cfgid)
}

// string name = 3;
inline void MapCharacterPacket::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MapCharacterPacket::name() const {
  // @@protoc_insertion_point(field_get:game.MapCharacterPacket.name)
  return _internal_name();
}
inline void MapCharacterPacket::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:game.MapCharacterPacket.name)
}
inline std::string* MapCharacterPacket::mutable_name() {
  // @@protoc_insertion_point(field_mutable:game.MapCharacterPacket.name)
  return _internal_mutable_name();
}
inline const std::string& MapCharacterPacket::_internal_name() const {
  return name_.GetNoArena();
}
inline void MapCharacterPacket::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MapCharacterPacket::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:game.MapCharacterPacket.name)
}
inline void MapCharacterPacket::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:game.MapCharacterPacket.name)
}
inline void MapCharacterPacket::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:game.MapCharacterPacket.name)
}
inline std::string* MapCharacterPacket::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MapCharacterPacket::release_name() {
  // @@protoc_insertion_point(field_release:game.MapCharacterPacket.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MapCharacterPacket::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:game.MapCharacterPacket.name)
}

// .game.VectorPacket pos = 4;
inline bool MapCharacterPacket::_internal_has_pos() const {
  return this != internal_default_instance() && pos_ != nullptr;
}
inline bool MapCharacterPacket::has_pos() const {
  return _internal_has_pos();
}
inline const ::game::VectorPacket& MapCharacterPacket::_internal_pos() const {
  const ::game::VectorPacket* p = pos_;
  return p != nullptr ? *p : *reinterpret_cast<const ::game::VectorPacket*>(
      &::game::_VectorPacket_default_instance_);
}
inline const ::game::VectorPacket& MapCharacterPacket::pos() const {
  // @@protoc_insertion_point(field_get:game.MapCharacterPacket.pos)
  return _internal_pos();
}
inline ::game::VectorPacket* MapCharacterPacket::release_pos() {
  // @@protoc_insertion_point(field_release:game.MapCharacterPacket.pos)
  
  ::game::VectorPacket* temp = pos_;
  pos_ = nullptr;
  return temp;
}
inline ::game::VectorPacket* MapCharacterPacket::_internal_mutable_pos() {
  
  if (pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::game::VectorPacket>(GetArenaNoVirtual());
    pos_ = p;
  }
  return pos_;
}
inline ::game::VectorPacket* MapCharacterPacket::mutable_pos() {
  // @@protoc_insertion_point(field_mutable:game.MapCharacterPacket.pos)
  return _internal_mutable_pos();
}
inline void MapCharacterPacket::set_allocated_pos(::game::VectorPacket* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(pos_);
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:game.MapCharacterPacket.pos)
}

// .game.VectorPacket face = 5;
inline bool MapCharacterPacket::_internal_has_face() const {
  return this != internal_default_instance() && face_ != nullptr;
}
inline bool MapCharacterPacket::has_face() const {
  return _internal_has_face();
}
inline const ::game::VectorPacket& MapCharacterPacket::_internal_face() const {
  const ::game::VectorPacket* p = face_;
  return p != nullptr ? *p : *reinterpret_cast<const ::game::VectorPacket*>(
      &::game::_VectorPacket_default_instance_);
}
inline const ::game::VectorPacket& MapCharacterPacket::face() const {
  // @@protoc_insertion_point(field_get:game.MapCharacterPacket.face)
  return _internal_face();
}
inline ::game::VectorPacket* MapCharacterPacket::release_face() {
  // @@protoc_insertion_point(field_release:game.MapCharacterPacket.face)
  
  ::game::VectorPacket* temp = face_;
  face_ = nullptr;
  return temp;
}
inline ::game::VectorPacket* MapCharacterPacket::_internal_mutable_face() {
  
  if (face_ == nullptr) {
    auto* p = CreateMaybeMessage<::game::VectorPacket>(GetArenaNoVirtual());
    face_ = p;
  }
  return face_;
}
inline ::game::VectorPacket* MapCharacterPacket::mutable_face() {
  // @@protoc_insertion_point(field_mutable:game.MapCharacterPacket.face)
  return _internal_mutable_face();
}
inline void MapCharacterPacket::set_allocated_face(::game::VectorPacket* face) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(face_);
  }
  if (face) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      face = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, face, submessage_arena);
    }
    
  } else {
    
  }
  face_ = face;
  // @@protoc_insertion_point(field_set_allocated:game.MapCharacterPacket.face)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace game

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_map_5fpacket_2eproto
