// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_game_login.proto

#ifndef PROTOBUF_msg_5fgame_5flogin_2eproto__INCLUDED
#define PROTOBUF_msg_5fgame_5flogin_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace game {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_5fgame_5flogin_2eproto();
void protobuf_AssignDesc_msg_5fgame_5flogin_2eproto();
void protobuf_ShutdownFile_msg_5fgame_5flogin_2eproto();

class CharacterPacket;

// ===================================================================

class CharacterPacket : public ::google::protobuf::Message {
 public:
  CharacterPacket();
  virtual ~CharacterPacket();

  CharacterPacket(const CharacterPacket& from);

  inline CharacterPacket& operator=(const CharacterPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CharacterPacket& default_instance();

  void Swap(CharacterPacket* other);

  // implements Message ----------------------------------------------

  CharacterPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CharacterPacket& from);
  void MergeFrom(const CharacterPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 account = 1;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 1;
  inline ::google::protobuf::uint64 account() const;
  inline void set_account(::google::protobuf::uint64 value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required int32 level = 3;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 3;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // required int32 exp = 4;
  inline bool has_exp() const;
  inline void clear_exp();
  static const int kExpFieldNumber = 4;
  inline ::google::protobuf::int32 exp() const;
  inline void set_exp(::google::protobuf::int32 value);

  // required int32 gem = 5;
  inline bool has_gem() const;
  inline void clear_gem();
  static const int kGemFieldNumber = 5;
  inline ::google::protobuf::int32 gem() const;
  inline void set_gem(::google::protobuf::int32 value);

  // required int32 coin = 6;
  inline bool has_coin() const;
  inline void clear_coin();
  static const int kCoinFieldNumber = 6;
  inline ::google::protobuf::int32 coin() const;
  inline void set_coin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:game.CharacterPacket)
 private:
  inline void set_has_account();
  inline void clear_has_account();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_exp();
  inline void clear_has_exp();
  inline void set_has_gem();
  inline void clear_has_gem();
  inline void set_has_coin();
  inline void clear_has_coin();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 account_;
  ::std::string* name_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 exp_;
  ::google::protobuf::int32 gem_;
  ::google::protobuf::int32 coin_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_msg_5fgame_5flogin_2eproto();
  friend void protobuf_AssignDesc_msg_5fgame_5flogin_2eproto();
  friend void protobuf_ShutdownFile_msg_5fgame_5flogin_2eproto();

  void InitAsDefaultInstance();
  static CharacterPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// CharacterPacket

// required uint64 account = 1;
inline bool CharacterPacket::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CharacterPacket::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CharacterPacket::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CharacterPacket::clear_account() {
  account_ = GOOGLE_ULONGLONG(0);
  clear_has_account();
}
inline ::google::protobuf::uint64 CharacterPacket::account() const {
  return account_;
}
inline void CharacterPacket::set_account(::google::protobuf::uint64 value) {
  set_has_account();
  account_ = value;
}

// required string name = 2;
inline bool CharacterPacket::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CharacterPacket::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CharacterPacket::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CharacterPacket::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& CharacterPacket::name() const {
  return *name_;
}
inline void CharacterPacket::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void CharacterPacket::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void CharacterPacket::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CharacterPacket::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* CharacterPacket::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CharacterPacket::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 level = 3;
inline bool CharacterPacket::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CharacterPacket::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CharacterPacket::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CharacterPacket::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 CharacterPacket::level() const {
  return level_;
}
inline void CharacterPacket::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// required int32 exp = 4;
inline bool CharacterPacket::has_exp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CharacterPacket::set_has_exp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CharacterPacket::clear_has_exp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CharacterPacket::clear_exp() {
  exp_ = 0;
  clear_has_exp();
}
inline ::google::protobuf::int32 CharacterPacket::exp() const {
  return exp_;
}
inline void CharacterPacket::set_exp(::google::protobuf::int32 value) {
  set_has_exp();
  exp_ = value;
}

// required int32 gem = 5;
inline bool CharacterPacket::has_gem() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CharacterPacket::set_has_gem() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CharacterPacket::clear_has_gem() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CharacterPacket::clear_gem() {
  gem_ = 0;
  clear_has_gem();
}
inline ::google::protobuf::int32 CharacterPacket::gem() const {
  return gem_;
}
inline void CharacterPacket::set_gem(::google::protobuf::int32 value) {
  set_has_gem();
  gem_ = value;
}

// required int32 coin = 6;
inline bool CharacterPacket::has_coin() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CharacterPacket::set_has_coin() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CharacterPacket::clear_has_coin() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CharacterPacket::clear_coin() {
  coin_ = 0;
  clear_has_coin();
}
inline ::google::protobuf::int32 CharacterPacket::coin() const {
  return coin_;
}
inline void CharacterPacket::set_coin(::google::protobuf::int32 value) {
  set_has_coin();
  coin_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace game

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5fgame_5flogin_2eproto__INCLUDED
