// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_game_map_switch.proto

#include "msg_game_map_switch.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace game {
class SwitchMapRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SwitchMapRequest> _instance;
} _SwitchMapRequest_default_instance_;
}  // namespace game
static void InitDefaultsscc_info_SwitchMapRequest_msg_5fgame_5fmap_5fswitch_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_SwitchMapRequest_default_instance_;
    new (ptr) ::game::SwitchMapRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::game::SwitchMapRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SwitchMapRequest_msg_5fgame_5fmap_5fswitch_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SwitchMapRequest_msg_5fgame_5fmap_5fswitch_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_msg_5fgame_5fmap_5fswitch_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_msg_5fgame_5fmap_5fswitch_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_msg_5fgame_5fmap_5fswitch_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_msg_5fgame_5fmap_5fswitch_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::SwitchMapRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::SwitchMapRequest, mapid_),
  PROTOBUF_FIELD_OFFSET(::game::SwitchMapRequest, type_),
  PROTOBUF_FIELD_OFFSET(::game::SwitchMapRequest, cfgid_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::game::SwitchMapRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_SwitchMapRequest_default_instance_),
};

const char descriptor_table_protodef_msg_5fgame_5fmap_5fswitch_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031msg_game_map_switch.proto\022\004game\">\n\020Swi"
  "tchMapRequest\022\r\n\005mapid\030\001 \001(\r\022\014\n\004type\030\002 \001"
  "(\005\022\r\n\005cfgId\030\003 \001(\rb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto_sccs[1] = {
  &scc_info_SwitchMapRequest_msg_5fgame_5fmap_5fswitch_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto_once;
static bool descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto = {
  &descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto_initialized, descriptor_table_protodef_msg_5fgame_5fmap_5fswitch_2eproto, "msg_game_map_switch.proto", 105,
  &descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto_once, descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto_sccs, descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_msg_5fgame_5fmap_5fswitch_2eproto::offsets,
  file_level_metadata_msg_5fgame_5fmap_5fswitch_2eproto, 1, file_level_enum_descriptors_msg_5fgame_5fmap_5fswitch_2eproto, file_level_service_descriptors_msg_5fgame_5fmap_5fswitch_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_msg_5fgame_5fmap_5fswitch_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_msg_5fgame_5fmap_5fswitch_2eproto), true);
namespace game {

// ===================================================================

void SwitchMapRequest::InitAsDefaultInstance() {
}
class SwitchMapRequest::_Internal {
 public:
};

SwitchMapRequest::SwitchMapRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:game.SwitchMapRequest)
}
SwitchMapRequest::SwitchMapRequest(const SwitchMapRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&mapid_, &from.mapid_,
    static_cast<size_t>(reinterpret_cast<char*>(&cfgid_) -
    reinterpret_cast<char*>(&mapid_)) + sizeof(cfgid_));
  // @@protoc_insertion_point(copy_constructor:game.SwitchMapRequest)
}

void SwitchMapRequest::SharedCtor() {
  ::memset(&mapid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cfgid_) -
      reinterpret_cast<char*>(&mapid_)) + sizeof(cfgid_));
}

SwitchMapRequest::~SwitchMapRequest() {
  // @@protoc_insertion_point(destructor:game.SwitchMapRequest)
  SharedDtor();
}

void SwitchMapRequest::SharedDtor() {
}

void SwitchMapRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SwitchMapRequest& SwitchMapRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SwitchMapRequest_msg_5fgame_5fmap_5fswitch_2eproto.base);
  return *internal_default_instance();
}


void SwitchMapRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:game.SwitchMapRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&mapid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cfgid_) -
      reinterpret_cast<char*>(&mapid_)) + sizeof(cfgid_));
  _internal_metadata_.Clear();
}

const char* SwitchMapRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 mapid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          mapid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 cfgId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          cfgid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SwitchMapRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.SwitchMapRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 mapid = 1;
  if (this->mapid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_mapid(), target);
  }

  // int32 type = 2;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_type(), target);
  }

  // uint32 cfgId = 3;
  if (this->cfgid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_cfgid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.SwitchMapRequest)
  return target;
}

size_t SwitchMapRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.SwitchMapRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 mapid = 1;
  if (this->mapid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_mapid());
  }

  // int32 type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_type());
  }

  // uint32 cfgId = 3;
  if (this->cfgid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_cfgid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SwitchMapRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.SwitchMapRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const SwitchMapRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SwitchMapRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.SwitchMapRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.SwitchMapRequest)
    MergeFrom(*source);
  }
}

void SwitchMapRequest::MergeFrom(const SwitchMapRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.SwitchMapRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.mapid() != 0) {
    _internal_set_mapid(from._internal_mapid());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
  if (from.cfgid() != 0) {
    _internal_set_cfgid(from._internal_cfgid());
  }
}

void SwitchMapRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.SwitchMapRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SwitchMapRequest::CopyFrom(const SwitchMapRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.SwitchMapRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SwitchMapRequest::IsInitialized() const {
  return true;
}

void SwitchMapRequest::InternalSwap(SwitchMapRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(mapid_, other->mapid_);
  swap(type_, other->type_);
  swap(cfgid_, other->cfgid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SwitchMapRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::game::SwitchMapRequest* Arena::CreateMaybeMessage< ::game::SwitchMapRequest >(Arena* arena) {
  return Arena::CreateInternal< ::game::SwitchMapRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
