// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sender_packet.proto

#include "sender_packet.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace game {
class SenderPacketDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SenderPacket> _instance;
} _SenderPacket_default_instance_;
}  // namespace game
static void InitDefaultsscc_info_SenderPacket_sender_5fpacket_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_SenderPacket_default_instance_;
    new (ptr) ::game::SenderPacket();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::game::SenderPacket::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SenderPacket_sender_5fpacket_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SenderPacket_sender_5fpacket_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_sender_5fpacket_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_sender_5fpacket_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_sender_5fpacket_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_sender_5fpacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::SenderPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::SenderPacket, sender_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::game::SenderPacket)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_SenderPacket_default_instance_),
};

const char descriptor_table_protodef_sender_5fpacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023sender_packet.proto\022\004game\"\036\n\014SenderPac"
  "ket\022\016\n\006sender\030\001 \001(\004b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_sender_5fpacket_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_sender_5fpacket_2eproto_sccs[1] = {
  &scc_info_SenderPacket_sender_5fpacket_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_sender_5fpacket_2eproto_once;
static bool descriptor_table_sender_5fpacket_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sender_5fpacket_2eproto = {
  &descriptor_table_sender_5fpacket_2eproto_initialized, descriptor_table_protodef_sender_5fpacket_2eproto, "sender_packet.proto", 67,
  &descriptor_table_sender_5fpacket_2eproto_once, descriptor_table_sender_5fpacket_2eproto_sccs, descriptor_table_sender_5fpacket_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_sender_5fpacket_2eproto::offsets,
  file_level_metadata_sender_5fpacket_2eproto, 1, file_level_enum_descriptors_sender_5fpacket_2eproto, file_level_service_descriptors_sender_5fpacket_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_sender_5fpacket_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_sender_5fpacket_2eproto), true);
namespace game {

// ===================================================================

void SenderPacket::InitAsDefaultInstance() {
}
class SenderPacket::_Internal {
 public:
};

SenderPacket::SenderPacket()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:game.SenderPacket)
}
SenderPacket::SenderPacket(const SenderPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sender_ = from.sender_;
  // @@protoc_insertion_point(copy_constructor:game.SenderPacket)
}

void SenderPacket::SharedCtor() {
  sender_ = PROTOBUF_ULONGLONG(0);
}

SenderPacket::~SenderPacket() {
  // @@protoc_insertion_point(destructor:game.SenderPacket)
  SharedDtor();
}

void SenderPacket::SharedDtor() {
}

void SenderPacket::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SenderPacket& SenderPacket::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SenderPacket_sender_5fpacket_2eproto.base);
  return *internal_default_instance();
}


void SenderPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:game.SenderPacket)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sender_ = PROTOBUF_ULONGLONG(0);
  _internal_metadata_.Clear();
}

const char* SenderPacket::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 sender = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          sender_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SenderPacket::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.SenderPacket)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 sender = 1;
  if (this->sender() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_sender(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.SenderPacket)
  return target;
}

size_t SenderPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.SenderPacket)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 sender = 1;
  if (this->sender() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_sender());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SenderPacket::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.SenderPacket)
  GOOGLE_DCHECK_NE(&from, this);
  const SenderPacket* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SenderPacket>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.SenderPacket)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.SenderPacket)
    MergeFrom(*source);
  }
}

void SenderPacket::MergeFrom(const SenderPacket& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.SenderPacket)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sender() != 0) {
    _internal_set_sender(from._internal_sender());
  }
}

void SenderPacket::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.SenderPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SenderPacket::CopyFrom(const SenderPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.SenderPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SenderPacket::IsInitialized() const {
  return true;
}

void SenderPacket::InternalSwap(SenderPacket* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(sender_, other->sender_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SenderPacket::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::game::SenderPacket* Arena::CreateMaybeMessage< ::game::SenderPacket >(Arena* arena) {
  return Arena::CreateInternal< ::game::SenderPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
